packaging_format = 2

id = "bazarr"
name = "Bazarr"
description.en = "Automated subtitle downloading for Sonarr and Radarr"
description.fr = "Téléchargement automatique de sous-titres pour Sonarr et Radarr"

version = "1.4.1~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "GPL-3.0"
website = "https://bazarr.media"
admindoc = "https://wiki.bazarr.media"
code = "https://github.com/morpheus65535/bazarr"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/bazarr"

    [install.admin]
    type = "user"

[resources]
        [resources.sources.main]
        url = "https://github.com/morpheus65535/bazarr/archive/refs/tags/v1.4.1.tar.gz"
        sha256 = "854d6bdfc12a128f8e09cf26f229730d26501f7e68e07d52979a4237c49faab0"
        in_subdir = false
        autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"

    [resources.apt]
    packages = "libxml2-dev, libxslt1-dev, unrar-free, ffmpeg, libatlas-base-dev, python3-venv"
