test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    preinstall = """
	# sudo yunohost domain add arr.domain.tld
	# sudo yunohost app list | grep "radarr" || sudo yunohost app install https://github.com/YunoHost-Apps/radarr_ynh --force -a "domain=arr.domain.tld&path=/radarr&admin=package_checker"
	# sudo yunohost app list | grep "sonarr" || sudo yunohost app install https://github.com/YunoHost-Apps/sonarr_ynh --force -a "domain=arr.domain.tld&path=/sonarr&admin=package_checker"
    """
