#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# MODIFY THE CONFIGURATION FILE
#=================================================
ynh_script_progression "Updating the configuration file..."

if [ $change_path -eq 1 ]
then
	ynh_replace --match="base_url: .*" --replace="base_url: ${new_path:-/}" --file="$install_dir/data/config/config.yaml"

	ynh_store_file_checksum "$install_dir/data/config/config.yaml"
fi

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"  --wait_until="BAZARR is started" --timeout 30

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
